## Following is the inventory file which is used.
## [PROD]
## ip-172-31-83-90.ec2.internal URL=prod.google.com 
## 
## [DEV]
## ip-172-31-83-90.ec2.internal
## 
## [DEV:vars]
## URL=dev.google.com 

- name: Print values from inventory file 
  hosts: DEV 
  vars:
    URL: google.com
  tasks: 
    - debug: msg="URL == {{URL}}"

- name: Print values from inventory file 1
  hosts: DEV 
  tasks: 
    - debug: msg="URL == {{URL}}"

