- name: Demo on filters
  hosts: all
  vars:
    URL:  https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.13/bin/apache-tomcat-9.0.13.tar.gz
    FILENAME: "{{ URL.split('/') | last }}"
    DIRNAME: "{{FILENAME.split('.tar.gz') | first }}"
  tasks: 
    - debug: msg="{{DIRNAME}}"